using System.Collections.Generic;
using System.Globalization;
using System.IO;
using Oni.Collections;

namespace Oni.Dae.IO
{
	internal class ObjWriter
	{
		private int vBase = 1;

		private int vtBase = 1;

		private int vnBase = 1;

		private Set<Material> materials = new Set<Material>();

		private StreamWriter objWriter;

		private StreamWriter mtlWriter;

		internal static void WriteFile(string filePath, Scene scene)
		{
			ObjWriter objWriter = new ObjWriter();
			objWriter.Write(filePath, scene);
		}

		private void Write(string filePath, Scene scene)
		{
			using (objWriter = File.CreateText(filePath))
			{
				objWriter.WriteLine("# Generated by OniSplit v{0}", Utils.Version);
				objWriter.WriteLine();
				objWriter.WriteLine("mtllib {0}", Path.ChangeExtension(Path.GetFileName(filePath), ".mtl"));
				objWriter.WriteLine();
				Matrix parentTransform = Matrix.Identity;
				WriteNode(scene, ref parentTransform);
			}
			using (mtlWriter = File.CreateText(Path.ChangeExtension(filePath, ".mtl")))
			{
				mtlWriter.WriteLine("# Generated by OniSplit v{0}", Utils.Version);
				mtlWriter.WriteLine();
				WriteMaterialLibrary();
			}
		}

		private void WriteNode(Node node, ref Matrix parentTransform)
		{
			if (!string.IsNullOrEmpty(node.Name))
			{
				objWriter.WriteLine("g {0}", node.Name);
			}
			Matrix parentTransform2 = node.Transforms.ToMatrix() * parentTransform;
			foreach (GeometryInstance geometryInstance in node.GeometryInstances)
			{
				WriteGeometry(geometryInstance, ref parentTransform2);
			}
			foreach (Node node2 in node.Nodes)
			{
				WriteNode(node2, ref parentTransform2);
			}
		}

		private void WriteGeometry(GeometryInstance geometryInstance, ref Matrix transform)
		{
			Geometry target = geometryInstance.Target;
			foreach (MeshPrimitives primitive in target.Primitives)
			{
				IndexedInput indexedInput = WritePositions(primitive, ref transform);
				IndexedInput indexedInput2 = WriteTexCoords(primitive);
				IndexedInput indexedInput3 = WriteNormals(primitive, ref transform);
				WriteUseMaterial(geometryInstance, primitive);
				WriteFaces(primitive, indexedInput, indexedInput2, indexedInput3);
				vBase += indexedInput.Source.Count;
				vtBase += ((indexedInput2 != null) ? indexedInput2.Source.Count : 0);
				vnBase += ((indexedInput3 != null) ? indexedInput3.Source.Count : 0);
			}
		}

		private IndexedInput WritePositions(MeshPrimitives primitives, ref Matrix transform)
		{
			IndexedInput indexedInput = primitives.Inputs.FirstOrDefault((IndexedInput i) => i.Semantic == Semantic.Position);
			Source source = indexedInput.Source;
			for (int num = 0; num < source.Count; num++)
			{
				Vector3 vector = Vector3.Transform(Source.ReadVector3(source, num), ref transform);
				objWriter.Write("v ");
				objWriter.Write(vector.X.ToString(CultureInfo.InvariantCulture));
				objWriter.Write(' ');
				objWriter.Write(vector.Y.ToString(CultureInfo.InvariantCulture));
				objWriter.Write(' ');
				objWriter.Write(vector.Z.ToString(CultureInfo.InvariantCulture));
				objWriter.WriteLine();
			}
			objWriter.WriteLine();
			return indexedInput;
		}

		private IndexedInput WriteTexCoords(MeshPrimitives primitives)
		{
			IndexedInput indexedInput = primitives.Inputs.FirstOrDefault((IndexedInput i) => i.Semantic == Semantic.TexCoord);
			if (indexedInput == null)
			{
				return null;
			}
			Source source = indexedInput.Source;
			float[] floatData = source.FloatData;
			for (int num = 0; num < floatData.Length; num += source.Stride)
			{
				objWriter.Write("vt ");
				objWriter.Write(floatData[num].ToString(CultureInfo.InvariantCulture));
				objWriter.Write(' ');
				objWriter.Write(floatData[num + 1].ToString(CultureInfo.InvariantCulture));
				objWriter.WriteLine();
			}
			objWriter.WriteLine();
			return indexedInput;
		}

		private IndexedInput WriteNormals(MeshPrimitives primitives, ref Matrix transform)
		{
			IndexedInput indexedInput = primitives.Inputs.FirstOrDefault((IndexedInput i) => i.Semantic == Semantic.Normal);
			if (indexedInput == null)
			{
				return null;
			}
			Source source = indexedInput.Source;
			for (int num = 0; num < source.Count; num++)
			{
				Vector3 vector = Vector3.TransformNormal(Source.ReadVector3(source, num), ref transform);
				objWriter.Write("vn ");
				objWriter.Write(vector.X.ToString(CultureInfo.InvariantCulture));
				objWriter.Write(' ');
				objWriter.Write(vector.Y.ToString(CultureInfo.InvariantCulture));
				objWriter.Write(' ');
				objWriter.Write(vector.Z.ToString(CultureInfo.InvariantCulture));
				objWriter.WriteLine();
			}
			objWriter.WriteLine();
			return indexedInput;
		}

		private void WriteFaces(MeshPrimitives primitives, IndexedInput posInput, IndexedInput texCoordInput, IndexedInput normalInput)
		{
			List<int> indices = posInput.Indices;
			List<int> list = ((texCoordInput == null) ? null : texCoordInput.Indices);
			List<int> list2 = ((normalInput == null) ? null : normalInput.Indices);
			int num = 0;
			foreach (int vertexCount in primitives.VertexCounts)
			{
				objWriter.Write("f");
				for (int i = num; i < num + vertexCount; i++)
				{
					objWriter.Write(' ');
					objWriter.Write((vBase + indices[i]).ToString(CultureInfo.InvariantCulture));
					if (list != null)
					{
						objWriter.Write('/');
						objWriter.Write((vtBase + list[i]).ToString(CultureInfo.InvariantCulture));
					}
					else if (list2 != null)
					{
						objWriter.Write('/');
					}
					if (list2 != null)
					{
						objWriter.Write('/');
						objWriter.Write((vnBase + list2[i]).ToString(CultureInfo.InvariantCulture));
					}
				}
				objWriter.WriteLine();
				num += vertexCount;
			}
			objWriter.WriteLine();
		}

		private void WriteUseMaterial(GeometryInstance geometryInstance, MeshPrimitives primitives)
		{
			if (string.IsNullOrEmpty(primitives.MaterialSymbol))
			{
				objWriter.WriteLine("usemtl");
				return;
			}
			MaterialInstance materialInstance = geometryInstance.Materials.Find((MaterialInstance m) => m.Symbol == primitives.MaterialSymbol);
			if (materialInstance != null && materialInstance.Target != null)
			{
				objWriter.WriteLine("usemtl {0}", materialInstance.Target.Name);
				materials.Add(materialInstance.Target);
			}
		}

		private void WriteMaterialLibrary()
		{
			foreach (Material material in materials)
			{
				mtlWriter.WriteLine("newmtl {0}", material.Name);
				Effect effect = material.Effect;
				WriteMaterialColor("Ka", effect.Ambient);
				WriteMaterialColor("Kd", effect.Diffuse);
				mtlWriter.WriteLine("Ks 0 0 0");
				mtlWriter.WriteLine("Ns 0");
				WriteMaterialTextureMap("map_Kd", effect.Diffuse);
				WriteMaterialTextureMap("map_Tr", effect.Transparent);
				if (effect.TransparentValue is EffectTexture)
				{
					mtlWriter.WriteLine("illum 9");
				}
				else
				{
					mtlWriter.WriteLine("illum 2");
				}
				mtlWriter.WriteLine();
			}
		}

		private void WriteMaterialColor(string mtlCommand, EffectParameter effectParam)
		{
			if (effectParam != null && effectParam.Value is Vector4)
			{
				Vector4 vector = (Vector4)effectParam.Value;
				mtlWriter.WriteLine(string.Format(CultureInfo.InvariantCulture, "{0} {1} {2} {3}", mtlCommand, vector.X, vector.Y, vector.Z));
			}
		}

		private void WriteMaterialTextureMap(string mtlCommand, EffectParameter effectParam)
		{
			if (effectParam != null)
			{
				EffectTexture effectTexture = effectParam.Value as EffectTexture;
				if (effectTexture != null)
				{
					mtlWriter.WriteLine("{0} {1}", mtlCommand, effectTexture.Sampler.Surface.InitFrom.FilePath);
				}
			}
		}
	}
}
